#!/bin/bash

cd "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-01.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-02.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-03.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-04.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-05.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-06.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-07.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-08.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-09.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-10.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-11.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-12.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-13.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-14.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-15.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-16.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-17.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-18.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-19.sh"
sbatch "/data/home/yb47324/share-lab/sims/src/manMCMedMiss/.sim/sum/sum-singularity-parallel-20.sh"
