---
title: "Containers"
author: Ivan Jacob Agaloos Pesigan
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Containers}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
#| include = FALSE
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

**[Docker](https://www.docker.com/) and [Apptainer](https://apptainer.org/) are required to build the containers described below.**

## Apptainer/Singularity Image File

The simulation was performed using the [Apptainer/Singularity](https://apptainer.org/) `manmcmedmiss.sif` image file. The image is an Archlinux container with the `manMCMedMiss` package  and all the dependencies pre-installed.

To build the Apptainer/Singularity image file (`manmcmedmiss.sif`),
run the following.

```bash
git clone https://github.com/jeksterslab/docker-manmcmedmiss.git
cd docker-manmcmedmiss
make
```

> **NOTE**: For complete reproducibility of the software stack, the actual `manmcmedmiss.sif` used in the simulations can be requested from the maintainer of this GitHub repository.

## RStudio IDE Docker Container

To facilitate exploration of the package, we created a Docker container based on the [Rocker Project](https://rocker-project.org/). The `manMCMedMiss` package and all the dependencies are pre-installed and can be accessed in the browser using the `Rstudio` IDE.

### Build

To build the container, run the following.

```bash
git clone https://github.com/jeksterslab/docker-manmcmedmiss-rocker.git
cd docker-manmcmedmiss-rocker
docker build -t manmcmedmiss-rocker .
```

### Run

To launch `Rstudio Server`, run the following.

```bash
docker run --rm -ti -e PASSWORD=yourpassword -p 8787:8787 manmcmedmiss-rocker
```

Open `http://localhost:8787` on your web browser to launch `Rstudio Server`.

- username: rstudio
- password: yourpassword
