---
title: "Session"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Session}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
#| include = FALSE
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, message = FALSE, eval = FALSE}
library(manMCMedMiss)
```

# Session

```{r, echo = FALSE, eval = FALSE}
sessionInfo()
```

```
#> R version 4.2.1 (2022-06-23)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Arch Linux
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/libopenblasp-r0.3.21.so
#> LAPACK: /usr/lib/liblapack.so.3.10.1
#> 
#> locale:
#>  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
#>  [4] LC_COLLATE=C           LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
#>  [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
#> [10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   
#> 
#> attached base packages:
#> [1] stats4    grid      stats     graphics  grDevices utils     datasets 
#> [8] methods   base     
#> 
#> other attached packages:
#>  [1] manMCMedMiss_0.9.1 party_1.3-10       strucchange_1.5-3  sandwich_3.0-2    
#>  [5] zoo_1.8-10         modeltools_0.2-23  mvtnorm_1.1-3      mice_3.14.0       
#>  [9] MASS_7.3-58.1      ggplot2_3.3.6     
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.9         pillar_1.8.1       compiler_4.2.1     lifecycle_1.0.1   
#>  [5] tibble_3.1.8       gtable_0.3.0       lattice_0.20-45    pkgconfig_2.0.3   
#>  [9] rlang_1.0.5        Matrix_1.4-1       cli_3.3.0.9000     parallel_4.2.1    
#> [13] libcoin_1.0-9      coin_1.4-2         withr_2.5.0        dplyr_1.0.9       
#> [17] generics_0.1.3     vctrs_0.4.1        tidyselect_1.1.2   glue_1.6.2        
#> [21] R6_2.5.1           fansi_1.0.3        survival_3.3-1     multcomp_1.4-20   
#> [25] TH.data_1.1-1      tidyr_1.2.0        purrr_0.3.4        magrittr_2.0.3    
#> [29] codetools_0.2-18   matrixStats_0.62.0 backports_1.4.1    scales_1.2.1      
#> [33] splines_4.2.1      colorspace_2.0-3   utf8_1.2.2         munsell_0.5.0     
#> [37] broom_1.0.1       
```

# CPU

```{r, echo = FALSE, eval = FALSE}
cat(system("lscpu", intern = TRUE), sep = "\n")
```

```
#> Architecture:          x86_64
#> CPU op-mode(s):        32-bit, 64-bit
#> Byte Order:            Little Endian
#> CPU(s):                4
#> On-line CPU(s) list:   0-3
#> Thread(s) per core:    1
#> Core(s) per socket:    4
#> Socket(s):             1
#> NUMA node(s):          1
#> Vendor ID:             GenuineIntel
#> CPU family:            6
#> Model:                 158
#> Model name:            Intel(R) Xeon(R) CPU E3-1280 v6 @ 3.90GHz
#> Stepping:              9
#> CPU MHz:               800.000
#> CPU max MHz:           3900.0000
#> CPU min MHz:           800.0000
#> BogoMIPS:              7824.00
#> Virtualization:        VT-x
#> L1d cache:             32K
#> L1i cache:             32K
#> L2 cache:              256K
#> L3 cache:              8192K
#> NUMA node0 CPU(s):     0-3
#> Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
```

# Memory

```{r, echo = FALSE, eval = FALSE}
cat(system("free -g -h -t", intern = TRUE), sep = "\n")
```

```
#>               total        used        free      shared  buff/cache   available
#> Mem:            62G        1.0G         52G        1.0G        9.2G         59G
#> Swap:          1.0G        2.2M        1.0G
#> Total:          63G        1.0G         53G
```
