#' Ampute Data
#'
#' The function generates a data set with missing values
#' for data generated by `GenData`
#' using the multivariate amputation approach.
#' See `mice::ampute()` for more details.
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @references
#' Schouten, R. M., Lugtig, P. and Vink, G. (2018).
#' Generating missing values for simulation purposes:
#' A multivariate amputation procedure.
#' *Journal of Statistical Computation and Simulation*,
#' *88*(15), 1909--1930.
#' \doi{10.1080/00949655.2018.1491577}
#'
#' @return Returns a dataframe.
#'
#' @inheritParams Template
#' @export
#' @family Data Generation Functions
#' @keywords manMCMedMiss gendata mediation ampute
AmputeData <- function(data_complete,
                       mech = "MAR",
                       prop = 0.30,
                       patterns = NULL) {
  if (is.null(patterns)) {
    patterns <- matrix(
      data = c(
        1, 0, 0,
        0, 1, 0,
        1, 1, 0,
        0, 0, 1,
        1, 0, 1,
        0, 1, 1
      ),
      ncol = 3,
      byrow = TRUE
    )
  }
  return(
    mice::ampute(
      data = data_complete,
      mech = mech,
      prop = prop,
      patterns = patterns
    )$amp
  )
}
