name: Make Project

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: ijapesigan/docs@sha256:0ec79e8efb879a81eb3df95d5208c12faf53259c68f63c0afdef20cad244ae4b
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      packages: read
      statuses: write

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Clone mpdemo-v8.8
        uses: GuillaumeFalourd/clone-github-repo-action@v2.1
        with:
          owner: 'jeksterslab'
          repository: 'mpdemo-v8.8'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      -
        name: Move 
        run: |
          pwd=$(pwd)
          cd mpdemo-v8.8
          mv mpdemo $pwd/.setup/bin
          cd ..
          rm -rf mpdemo-v8.8
      -
        name: Clean
        run: |
          make clean
      -
        name: Make Project
        run: |
          make install
          make push
      -
        name: Remove mpdemo-v8.8
        run: rm -rf .setup/bin/mpdemo
      - 
        name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Automated build."
